-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Object.Settings exposing (..)

import Graphql.Internal.Builder.Object as Object
import Graphql.Object
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as D


{-| -}
activityColor :
    SelectionSet decodesTo Graphql.Object.Color
    -> SelectionSet decodesTo Graphql.Object.Settings
activityColor object____ =
    Object.selectionForCompositeField "activityColor" [] object____ Basics.identity


{-| -}
backgroundColor : SelectionSet String Graphql.Object.Settings
backgroundColor =
    Object.selectionForField "String" "backgroundColor" [] D.string


{-| -}
font : SelectionSet String Graphql.Object.Settings
font =
    Object.selectionForField "String" "font" [] D.string


{-| -}
height : SelectionSet Int Graphql.Object.Settings
height =
    Object.selectionForField "Int" "height" [] D.int


{-| -}
labelColor : SelectionSet String Graphql.Object.Settings
labelColor =
    Object.selectionForField "String" "labelColor" [] D.string


{-| -}
lineColor : SelectionSet String Graphql.Object.Settings
lineColor =
    Object.selectionForField "String" "lineColor" [] D.string


{-| -}
scale : SelectionSet (Maybe Float) Graphql.Object.Settings
scale =
    Object.selectionForField "(Maybe Float)" "scale" [] (D.float |> D.nullable)


{-| -}
storyColor :
    SelectionSet decodesTo Graphql.Object.Color
    -> SelectionSet decodesTo Graphql.Object.Settings
storyColor object____ =
    Object.selectionForCompositeField "storyColor" [] object____ Basics.identity


{-| -}
taskColor :
    SelectionSet decodesTo Graphql.Object.Color
    -> SelectionSet decodesTo Graphql.Object.Settings
taskColor object____ =
    Object.selectionForCompositeField "taskColor" [] object____ Basics.identity


{-| -}
textColor : SelectionSet (Maybe String) Graphql.Object.Settings
textColor =
    Object.selectionForField "(Maybe String)" "textColor" [] (D.string |> D.nullable)


{-| -}
toolbar : SelectionSet (Maybe Bool) Graphql.Object.Settings
toolbar =
    Object.selectionForField "(Maybe Bool)" "toolbar" [] (D.bool |> D.nullable)


{-| -}
width : SelectionSet Int Graphql.Object.Settings
width =
    Object.selectionForField "Int" "width" [] D.int


{-| -}
zoomControl : SelectionSet (Maybe Bool) Graphql.Object.Settings
zoomControl =
    Object.selectionForField "(Maybe Bool)" "zoomControl" [] (D.bool |> D.nullable)
