-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Object.ShareCondition exposing (..)

import Graphql.Internal.Builder.Object as Object
import Graphql.Object
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as D


{-| -}
allowEmailList : SelectionSet (Maybe (List String)) Graphql.Object.ShareCondition
allowEmailList =
    Object.selectionForField "(Maybe (List String))" "allowEmailList" [] (D.string |> D.list |> D.nullable)


{-| -}
allowIPList : SelectionSet (Maybe (List String)) Graphql.Object.ShareCondition
allowIPList =
    Object.selectionForField "(Maybe (List String))" "allowIPList" [] (D.string |> D.list |> D.nullable)


{-| -}
expireTime : SelectionSet Int Graphql.Object.ShareCondition
expireTime =
    Object.selectionForField "Int" "expireTime" [] D.int


{-| -}
token : SelectionSet String Graphql.Object.ShareCondition
token =
    Object.selectionForField "String" "token" [] D.string


{-| -}
usePassword : SelectionSet Bool Graphql.Object.ShareCondition
usePassword =
    Object.selectionForField "Bool" "usePassword" [] D.bool
