-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TextUSM.Object.ShareCondition exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import TextUSM.InputObject
import TextUSM.Interface
import TextUSM.Object
import TextUSM.Scalar
import TextUSM.ScalarCodecs
import TextUSM.Union


{-| -}
token : SelectionSet String TextUSM.Object.ShareCondition
token =
    Object.selectionForField "String" "token" [] Decode.string


{-| -}
usePassword : SelectionSet Bool TextUSM.Object.ShareCondition
usePassword =
    Object.selectionForField "Bool" "usePassword" [] Decode.bool


{-| -}
expireTime : SelectionSet Int TextUSM.Object.ShareCondition
expireTime =
    Object.selectionForField "Int" "expireTime" [] Decode.int


{-| -}
allowIPList : SelectionSet (Maybe (List String)) TextUSM.Object.ShareCondition
allowIPList =
    Object.selectionForField "(Maybe (List String))" "allowIPList" [] (Decode.string |> Decode.list |> Decode.nullable)
