-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.ScalarCodecs exposing (..)

import Graphql.Scalar exposing (defaultCodecs)


codecs : Graphql.Scalar.Codecs Id Time
codecs =
    Graphql.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecTime = defaultCodecs.codecTime
        }


type alias Id =
    Graphql.Scalar.Id


type alias Time =
    Graphql.Scalar.Time
