version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gosec
    - gocritic
    - misspell
    - noctx
    - exhaustive
    - bodyclose
  settings:
    gosec:
      excludes:
        - G104
        - G115
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - ifElseChain

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck

formatters:
  enable:
    - gofmt
