alias g := generate

main := "cmd/api-server/main.go"
module := "github.com/harehare/textusm"
sec := "gosec"
target := "./..."

run:
	go run {{ main }}

build:
	go build -o dist/textusm {{ main }}

watch:
	go tool air -c .air.toml

build-linux:
	GOOS="linux" GOARCH="amd64" go build -o dist/textusm {{ main }}

embed-build:
	go build -tags embed -o textusm-embed {{ main }}

generate:
	go get golang.org/x/tools/go/packages
	go get golang.org/x/tools/go/ast/astutil
	go get golang.org/x/tools/imports
	go get github.com/urfave/cli/v2
	go generate {{ target }}

test:
	go test {{ target }} -cover {{ target }}

lint:
	go tool staticcheck {{ target }}
	go tool golangci-lint run {{ target }}
	go tool errcheck {{ target }}
	go tool gosec -quiet {{ target }}

fix:
	go tool fieldalignment -fix pkg/domain/model/item/gistitem/gistitem.go
	go tool fieldalignment -fix pkg/domain/model/item/gistitem/gistitem.go
	go tool fieldalignment -fix pkg/presentation/graphql/models.go

migrate:
	DBMATE_SCHEMA_FILE=db/${DB_TYPE}/schema.sql go tool dbmate -d db/${DB_TYPE}/migrations up
	DBMATE_SCHEMA_FILE=db/${DB_TYPE}/schema.sql go tool dbmate dump

rollback:
	DBMATE_SCHEMA_FILE=db/${DB_TYPE}/schema.sql go tool dbmate -d db/${DB_TYPE}/migrations down

check:
	go mod tidy && git diff -s --exit-code -- go.sum
	go tool wire check {{target}}
