alias g := generate

main := "cmd/api-server/main.go"
module := "github.com/harehare/textusm"
sec := "gosec"
target := "./..."

install-tools:
  go install honnef.co/go/tools/cmd/staticcheck@latest
  go install github.com/securego/gosec/v2/cmd/gosec@latest
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
  go install github.com/air-verse/air@latest
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

run:
	go run {{ main }}

build:
	go build -o dist/textusm {{ main }}

watch:
	air -c .air.toml

build-linux:
	GOOS="linux" GOARCH="amd64" go build -o dist/textusm {{ main }}

embed-build:
	go build -tags embed -o textusm-embed {{ main }}

generate:
	go get golang.org/x/tools/go/packages
	go get golang.org/x/tools/go/ast/astutil
	go get golang.org/x/tools/imports
	go get github.com/urfave/cli/v2
	go generate {{ target }}

test:
	go test {{ target }}

lintre:
	staticcheck {{ target }}
	gosec {{ target }}
	golangci-lint run {{ target }}


fix:
	fieldalignment -fix pkg/domain/model/item/gistitem/gistitem.go
	fieldalignment -fix pkg/domain/model/item/gistitem/gistitem.go
	fieldalignment -fix pkg/presentation/graphql/models.go

migrate:
  DBMATE_SCHEMA_FILE=db/${DB_TYPE}/schema.sql dbmate -d db/${DB_TYPE}/migrations up
  DBMATE_SCHEMA_FILE=db/${DB_TYPE}/schema.sql dbmate dump

rollback:
  DBMATE_SCHEMA_FILE=db/${DB_TYPE}/schema.sql dbmate -d db/${DB_TYPE}/migrations down
