alias g := generate

main := "cmd/api-server/main.go"
module := "github.com/harehare/textusm"
lint := "staticcheck"
sec := "gosec"
target := "./..."

setup:
  go get honnef.co/go/tools/cmd/staticcheck
  go get github.com/securego/gosec/v2/cmd/gosec
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
  go install github.com/cosmtrek/air@latest

run:
	go run {{ main }}

build:
	go build -o dist/textusm {{ main }}

watch:
	air -c .air.toml

build-linux:
	GOOS="linux" GOARCH="amd64" go build -o dist/textusm {{ main }}

embed-build:
	go build -tags embed -o textusm-embed {{ main }}

generate:
	go generate {{ target }}

test:
	go test {{ target }}

lint:
	{{ lint }} {{ module }}
	{{ sec }} {{ target }}

fix:
	fieldalignment -fix pkg/domain/model/item/gistitem/gistitem.go
	fieldalignment -fix pkg/domain/model/item/gistitem/gistitem.go
	fieldalignment -fix pkg/presentation/graphql/models.go
