-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TextUSM.Query exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import TextUSM.InputObject
import TextUSM.Interface
import TextUSM.Object
import TextUSM.Scalar
import TextUSM.ScalarCodecs
import TextUSM.Union


type alias ItemRequiredArguments =
    { id : String }


{-|

  - id -

-}
item : ItemRequiredArguments -> SelectionSet decodesTo TextUSM.Object.Item -> SelectionSet decodesTo RootQuery
item requiredArgs object_ =
    Object.selectionForCompositeField "item" [ Argument.required "id" requiredArgs.id Encode.string ] object_ identity


type alias ItemsOptionalArguments =
    { offset : OptionalArgument Int
    , limit : OptionalArgument Int
    , isBookmark : OptionalArgument Bool
    , isPublic : OptionalArgument Bool
    }


{-|

  - offset -
  - limit -
  - isBookmark -
  - isPublic -

-}
items : (ItemsOptionalArguments -> ItemsOptionalArguments) -> SelectionSet decodesTo TextUSM.Object.Item -> SelectionSet (List (Maybe decodesTo)) RootQuery
items fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { offset = Absent, limit = Absent, isBookmark = Absent, isPublic = Absent }

        optionalArgs =
            [ Argument.optional "offset" filledInOptionals.offset Encode.int, Argument.optional "limit" filledInOptionals.limit Encode.int, Argument.optional "isBookmark" filledInOptionals.isBookmark Encode.bool, Argument.optional "isPublic" filledInOptionals.isPublic Encode.bool ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "items" optionalArgs object_ (identity >> Decode.nullable >> Decode.list)
