-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TextUSM.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import TextUSM.Scalar exposing (defaultCodecs)


type alias Id =
    TextUSM.Scalar.Id


type alias Time =
    TextUSM.Scalar.Time


codecs : TextUSM.Scalar.Codecs Id Time
codecs =
    TextUSM.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecTime = defaultCodecs.codecTime
        }
