-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Object exposing (..)


type GistItem
    = GistItem


type Item
    = Item


type ShareCondition
    = ShareCondition
