-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Object exposing (Color(..), GistItem(..), Item(..), Settings(..), ShareCondition(..))


type Color
    = Color


type GistItem
    = GistItem


type Item
    = Item


type Settings
    = Settings


type ShareCondition
    = ShareCondition
