-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.ScalarCodecs exposing (..)

import Graphql.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Graphql.Scalar.Id


type alias ItemIdScalar =
    Graphql.Scalar.ItemIdScalar


type alias Time =
    Graphql.Scalar.Time


codecs : Graphql.Scalar.Codecs Id ItemIdScalar Time
codecs =
    Graphql.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecItemIdScalar = defaultCodecs.codecItemIdScalar
        , codecTime = defaultCodecs.codecTime
        }
