// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/harehare/textusm/pkg/domain/values"
)

type InputColor struct {
	ForegroundColor string `json:"foregroundColor"`
	BackgroundColor string `json:"backgroundColor"`
}

type InputGistItem struct {
	ID         *string         `json:"id"`
	Title      string          `json:"title"`
	Thumbnail  *string         `json:"thumbnail"`
	Diagram    *values.Diagram `json:"diagram"`
	IsBookmark bool            `json:"isBookmark"`
	URL        string          `json:"url"`
}

type InputItem struct {
	ID         *string         `json:"id"`
	Title      string          `json:"title"`
	Text       string          `json:"text"`
	Thumbnail  *string         `json:"thumbnail"`
	Diagram    *values.Diagram `json:"diagram"`
	IsPublic   bool            `json:"isPublic"`
	IsBookmark bool            `json:"isBookmark"`
}

type InputSettings struct {
	Font            string      `json:"font"`
	Width           int         `json:"width"`
	Height          int         `json:"height"`
	BackgroundColor string      `json:"backgroundColor"`
	ActivityColor   *InputColor `json:"activityColor"`
	TaskColor       *InputColor `json:"taskColor"`
	StoryColor      *InputColor `json:"storyColor"`
	LineColor       string      `json:"lineColor"`
	LabelColor      string      `json:"labelColor"`
	TextColor       *string     `json:"textColor"`
	ZoomControl     *bool       `json:"zoomControl"`
	Scale           *float64    `json:"scale"`
}

type InputShareItem struct {
	ItemID         string   `json:"itemID"`
	ExpSecond      *int     `json:"expSecond"`
	Password       *string  `json:"password"`
	AllowIPList    []string `json:"allowIPList"`
	AllowEmailList []string `json:"allowEmailList"`
}
