on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: frontend
      - name: tag is already existing to GITHUB_ENV
        run: |
          tag_is_existing=$(
            git fetch origin v${{ steps.package-version.outputs.current-version }} &&
            echo true ||
            echo false
          )
          echo "TAG_IS_EXISTING=${tag_is_existing}" >> $GITHUB_ENV
      - if: env.TAG_IS_EXISTING == 'false'
        run: |
          git tag v${{ steps.package-version.outputs.current-version }}
          git push origin v${{ steps.package-version.outputs.current-version }}
      - name: Build Changelog
        if: env.TAG_IS_EXISTING == 'false'
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        if: env.TAG_IS_EXISTING == 'false'
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: v${{ steps.package-version.outputs.current-version }}
          body: ${{steps.github_release.outputs.changelog}}
          allowUpdates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
